import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navber/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster"
import {Kanit} from "next/font/google";


const kannit = Kanit({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "600", "700"], 
  style: ["italic","normal"],                  
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KingCamp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      elements:{
        footer: "hidden",
      }
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${kannit.className} antialiased`}
      >
        <Providers>
        <Navbar />
        <main className="ctn">
        {children}
        </main>
        </Providers>

      </body>
    </html>
    </ClerkProvider>
  );
}
